version: "3.7"

services:
  database: 
    image: postgres
    container_name: database_rentx
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    networks: 
      - ignite-network
  app:
    build: .
    container_name: rentx
    ports:
      - 3000:3000
    volumes: 
      - .:/usr/app
    depends_on:
      - database
    networks: 
      - ignite-network

networks: 
    ignite-network:
      driver: bridge

volumes: 
  pgdata:
    driver: local